### ISSUE TITLE
Finnish flag not working at all

### ISSUE THREAD

**Issue by zhelly0** [Franc1sco/Franug-CountryFlagIcons#2]
Finnish flag doesn't seem to apply at all, not sure what more i can say :P I would fix it myself but all the math in the code gives me a headache :D

**Comment by Franc1sco** [comment]
You dont need to edit the code, just the cfg file. Add the "FI" (Finnish code2 country) with the correct index (if exist that flag currently in the repo) or upload a new flag yourself (with the same size that the others flags) and with a index not used currently.

**Comment by zhelly0** [comment]
I see what has happened, you accidentally put FL instead of FI for the country in the config.

	"FL"
	{
		"index"		"1207"
	}

**Comment by Franc1sco** [comment]
Oh I see. Fixed, thanks.
